title: Ottawa Visuals
description: Data & dashboards
url: "https://ottawavisuals.github.io"
baseurl: "/Ottawa-Visuals"

# Dark mode skin
minimal_mistakes_skin: "dark"

# Use the theme (no Gemfile needed on GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes"

# GitHub Pages–allowed plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Site-wide UI
locale: en
timezone: America/Toronto
markdown: kramdown
permalink: /:title/
logo: /assets/img/avatar.png   # optional small logo in header

# Author box (left sidebar)
author:
  name: "Ottawa Visuals"
  avatar: "/assets/img/avatar.png"   # 200×200 suggested
  bio: "Public data • Power BI • Ottawa"
  links:
    - label: "Email"
      url: "mailto:Visuals@OttawaVisuals.onmicrosoft.com"
    - label: "GitHub"
      url: "https://github.com/Ottawa-Visuals"


# Enable nav from _data/navigation.yml
include: ["_pages"]
