title: Ottawa Visuals
description: Data & dashboards
lang: en
timezone: America/Toronto

# Use ONLY the remote theme (no `theme:` key)
remote_theme: cotes2020/jekyll-theme-chirpy

# Safe, supported plugins on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 10
